### ISSUE TITLE
Web service reads from S3 interface

### ISSUE THREAD

**Issue by robert-clegg-tessella** [ukaea/ditto#3]
**Reviewer:** Rob, Dan

A POST request to the Web API (route "listpresent", JSON body) returns a list of the files already present at the server end.
https://github.com/ukaea/ditto/pull/16

**Acceptance criteria:**
Both the web app and the S3 interface need to be up and running.

POST request to http://172.28.129.160:8888/listpresent/ with correctly formatted JSON body (e.g. http://172.28.129.160:8888/listpresent/ `{"bucket": "test-bucket-name", "directory": "testdir/testsubdir"}`) returns a JSON response

The relative path to directory is an optional argument (`{"bucket": "test-bucket-name"}` should also work). When it is absent all files should be returned.

* When the bucket does not exist a warning message should be returned
* When there are no files in the directory at the S3 end this should return an empty array
* When there are files in the directory at the S3 end this should return information for each one: name (including relative path), which bucket it is in, size in bytes, last modified (in UNIX time)

**Comment by daniel-hunt-tessella** [comment]
`"is_dir"` has now been removed which resolves the previous comment
