### ISSUE TITLE
Web app can make buckets

### ISSUE THREAD

**Issue by robert-clegg-tessella** [ukaea/ditto#34]
**Story points:** 2
**Reviewer:** Rob

A POST request to the Web API (route "createbucket") creates a bucket at the server end.

**Acceptance criteria:**
Both the web app and the S3 interface need to be up and running.

Bucket names are standardised: they must either start with `test-` or with `ditto-`. This standardisation should be specified in the configuration file.

POST request to http://172.28.129.160:8888/createbucket/{bucket-name} (e.g. http://172.28.129.160:8888/createbucket/ditto-example/) returns a JSON response confirming that the bucket was created

Returns a warning message (and makes no changes) if
* no bucket name is given in the route
* the bucket name does not fit the pattern specified in the configuration file
* a bucket of that name already exists

https://github.com/ukaea/ditto/pull/36

**Comment by daniel-hunt-tessella** [comment]
Note #71 will address incorrect status and status codes.

There is an additional issue - attempting to create a bucket with the name ditto-test-.test returns a 200 response which suggests that everything is fine and the bucket is created.

The bucket is not created however and the logs look like this:
```
2018-11-29 16:37:34,473 ditto-web-api DEBUG    Called create-bucket handler
DEBUG:ditto-web-api:Called create-bucket handler
2018-11-29 16:37:34,476 ditto-web-api DEBUG    Bucket "ditto-twentyninth.-135678asdf" does not exist
DEBUG:ditto-web-api:Bucket "ditto-twentyninth.-135678asdf" does not exist
2018-11-29 16:37:34,483 ditto-web-api ERROR    S3ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidBucketName</Code><Message>The specified bucket is not valid.</Message><Resource>/ditto-twentyninth.-135678asdf/</Resource><RequestId>156BA5ABC59D794F</RequestId><HostId>3L137</HostId></Error>
ERROR:ditto-web-api:S3ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidBucketName</Code><Message>The specified bucket is not valid.</Message><Resource>/ditto-twentyninth.-135678asdf/</Resource><RequestId>156BA5ABC59D794F</RequestId><HostId>3L137</HostId></Error>
2018-11-29 16:37:34,483 ditto-web-api DEBUG    Could not create bucket "ditto-twentyninth.-135678asdf"
DEBUG:ditto-web-api:Could not create bucket "ditto-twentyninth.-135678asdf"
```

**Comment by daniel-hunt-tessella** [comment]
The status code issues and `-.` bucket issue have been resolved since the last comment. The bucket creation process has changed with #67 and #82 so the functionality will be tested for those stories
