### ISSUE TITLE
Investigate S3 bucket locations

### ISSUE THREAD

**Issue by oliver-tarrant-tessella** [ukaea/ditto#41]
When creating a new bucket need to specify where the bucket location is. e.g. us-east-1. Need to look at why this matters, what we need and if we need to configure. Currently used value is eu-west-1

**Comment by robert-clegg-tessella** [comment]
**Note:** Both the minio and the boto SDKs have default values for region in their bucket-creating methods. If the region value is ignored by the S3 interface being used then we may be able to ignore this.

**Comment by robert-clegg-tessella** [comment]
It seems that setting a region is confusing the S3 interface. `minio-py` always passes a region parameter (set to `"us-east-1"` by default if none is given). We may have more luck using `boto` instead.

**Comment by daniel-hunt-tessella** [comment]
We have now switched from minio to boto as a result of this investigation and the system still works as before.
