### ISSUE TITLE
API is overly fussy

### ISSUE THREAD

**Issue by jholloc** [ukaea/ditto#60]
For requests, "http://url/listpresent/" is found but "http://url/listpresent" returns a 404. Does the API need to be this fussy? Would it cause issues to allow both formats?

**Comment by daniel-hunt-tessella** [comment]
**Testing**
* API requests work in both situations when they end in a / and when it is omitted as in the example above
* The same flexibility is also afforded in the specification of file paths - they can now start with a / and can omit it eg for /deletefile both these bodies will have the same effect:
`{"bucket": "ditto-anything-i-want", "file": "/test.txt"}`
`{"bucket": "ditto-anything-i-want", "file": "test.txt"}`
