### ISSUE TITLE
BucketConfigService to link each bucket to a root directory and to user group(s)

### ISSUE THREAD

**Issue by robert-clegg-tessella** [ukaea/ditto#74]
Note that tasks related to `createbucket` are in separate issues:
* (#67) only `admin` users can create buckets
* (#82) when creating a bucket, the bucket settings file is updated

Therefore, these tasks are not covered in this PR.

**Acceptance criteria:** 
A `bucket_settings.ini` file must be written in in `ditto_web_api/DittoWebApi`, using `example_bucket_settings.ini` as a template. Note that the group tags for each bucket will be those used to compare against the groups tags in `security_configuration.ini`

Confirm that a user can only interact with a bucket that they have authorisation for: i.e. one or more of the groups they belong to is on the list of groups for that bucket. Any un-authorised requests should return a 403 error.

**Comment by daniel-hunt-tessella** [comment]
Testing:
* Create a bucket as an admin user (an admin user is a user assigned to an admin group - can be checked in security_configuration.ini and configuration.ini) ✔️ 
* View the bucket_settings.ini file - this contains the bucket name, the groups and the roots for this new bucket ✔️ 
* Attempt to create a bucket as a non-admin user - this will fail with a 403 error ✔️ 
* Attempt to access the contents of a bucket as a user that is not a member of any of the groups associated with that bucket - this will return a 403 error. Use several different API calls to test this ✔️
